### ISSUE TITLE
Cowhook on top

### ISSUE THREAD

**Issue by AdultSwim1234** [RosneBurgerworks/rosnebot-database#6]
COWHOOK, THE BEST TF2 CHEAT. PUTS RATHOOK, LMAOBOX, ROSNEHOOK, AND RIJIN TO SHAME! ONETF2 CREATED COWHOOK BY PUTTING CONST CHAR ON THE LABEL!!!

**Comment by rosne-gamingyt** [comment]
true

**Comment by pixelwarrior99** [comment]
What is this

**Comment by rosne-gamingyt** [comment]
> What is this

Cowhook on top??
